//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ArgsHidden.exe.
        /// </summary>
        internal static string argsHidden {
            get {
                return ResourceManager.GetString("argsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please associate .xpadder file extension with XPadder..
        /// </summary>
        internal static string Associate {
            get {
                return ResourceManager.GetString("Associate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -  Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost Heatsink Fan.
        /// </summary>
        internal static string Fan {
            get {
                return ResourceManager.GetString("Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \FanControl.exe.
        /// </summary>
        internal static string FanControl {
            get {
                return ResourceManager.GetString("FanControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FanOff {
            get {
                return ResourceManager.GetString("FanOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string FanOn {
            get {
                return ResourceManager.GetString("FanOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FanTray {
            get {
                object obj = ResourceManager.GetObject("FanTray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game.
        /// </summary>
        internal static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHelper.
        /// </summary>
        internal static string GHelper {
            get {
                return ResourceManager.GetString("GHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \GHelper.exe.
        /// </summary>
        internal static string GHelperExe {
            get {
                return ResourceManager.GetString("GHelperExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHelper - Fan (on).
        /// </summary>
        internal static string GHelperFanOn {
            get {
                return ResourceManager.GetString("GHelperFanOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /task C:\Windows\System32\schtasks.exe /run /tn &quot;GHelperLite&quot;.
        /// </summary>
        internal static string GHelperLiteStart {
            get {
                return ResourceManager.GetString("GHelperLiteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /task C:\Windows\System32\schtasks.exe /run /tn &quot;GHelper&quot;.
        /// </summary>
        internal static string GHelperStart {
            get {
                return ResourceManager.GetString("GHelperStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /task C:\Windows\System32\schtasks.exe /run /tn &quot;GHelper_Logon&quot;.
        /// </summary>
        internal static string GHelperStartLogon {
            get {
                return ResourceManager.GetString("GHelperStartLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON {
            get {
                object obj = ResourceManager.GetObject("ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -  .
        /// </summary>
        internal static string LogSpace {
            get {
                return ResourceManager.GetString("LogSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShadowEx.
        /// </summary>
        internal static string OpenShadowEx {
            get {
                return ResourceManager.GetString("OpenShadowEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xpadder.
        /// </summary>
        internal static string OpenXpadder {
            get {
                return ResourceManager.GetString("OpenXpadder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Please reboot to resolve this issue..
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinitialize.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file has been changed.
        ///
        ///Please press OK when you are done changing settings and GHelper will be restarted..
        /// </summary>
        internal static string SettingsChanged {
            get {
                return ResourceManager.GetString("SettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ShadowEx.exe.
        /// </summary>
        internal static string ShadowEx {
            get {
                return ResourceManager.GetString("ShadowEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -shutdown.
        /// </summary>
        internal static string ShutDown {
            get {
                return ResourceManager.GetString("ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -start.
        /// </summary>
        internal static string startShadowEx {
            get {
                return ResourceManager.GetString("startShadowEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatsink fan (normal).
        /// </summary>
        internal static string StopFan {
            get {
                return ResourceManager.GetString("StopFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Waiting for Game.
        /// </summary>
        internal static string StopWaiting {
            get {
                return ResourceManager.GetString("StopWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USBDetect.
        /// </summary>
        internal static string USBDetect {
            get {
                return ResourceManager.GetString("USBDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xpadder.
        /// </summary>
        internal static string Xpadder {
            get {
                return ResourceManager.GetString("Xpadder", resourceCulture);
            }
        }
    }
}
